from __future__ import annotations

import asyncio
import uuid
from types import SimpleNamespace

from agents.pinn_agent import PINNAgent
from agents.tester import TestReport
from orchestrator.intent_engine import IntentEngine
from orchestrator.vector_gate import VectorGate
from schemas.project_plan import PlanAction, ProjectPlan
from schemas.world_model import WorldModel


def test_vector_gate_opens_with_matching_tokens():
    world_model = WorldModel()
    gate = VectorGate(min_similarity=0.05, top_k=2)

    # Token vectors are generated by PINN deterministic embedding; this keeps
    # retrieval behavior stable for test assertions.
    pinn = PINNAgent()
    token = pinn.ingest_artifact(
        artifact_id="arch-1",
        content="Authentication service with JWT refresh tokens and RBAC.",
    )
    world_model.add_token(token)

    decision = gate.evaluate(
        node="coder_input",
        query="Build JWT authentication flow",
        world_model=world_model,
    )

    assert decision.is_open is True
    assert len(decision.matches) >= 1
    assert decision.matches[0].token_id == token.token_id


def test_intent_engine_injects_vector_gate_context(monkeypatch):
    engine = IntentEngine()

    # Seed a world-model token so legacy execute_plan can consume vector context.
    engine.architect.pinn.ingest_artifact(
        artifact_id="arch-ctx",
        content="Use strict input validation and parameterized SQL queries.",
    )

    captured_feedback = []
    captured_tester_context = []

    async def fake_generate_solution(parent_id, feedback=None):
        captured_feedback.append(feedback or "")
        return SimpleNamespace(
            artifact_id=str(uuid.uuid4()),
            content="def safe_query(): pass",
            metadata={},
        )

    async def fake_validate(_artifact_id, supplemental_context=None):
        captured_tester_context.append(supplemental_context or "")
        return TestReport(status="PASS", critique="Looks safe")

    monkeypatch.setattr(engine.coder, "generate_solution", fake_generate_solution)
    monkeypatch.setattr(engine.tester, "validate", fake_validate)
    monkeypatch.setattr(engine.db, "save_artifact", lambda artifact: artifact)

    plan = ProjectPlan(
        plan_id="plan-vg-1",
        project_name="vector-gate",
        requester="qa",
        actions=[
            PlanAction(
                action_id="a1",
                title="DB layer",
                instruction="Implement safe user query with tests",
            )
        ],
    )

    asyncio.run(engine.execute_plan(plan))

    assert captured_feedback
    assert "[VECTOR_GATE node=legacy_coder_input" in captured_feedback[0]
    assert captured_tester_context
    assert "[VECTOR_GATE node=legacy_tester_input" in captured_tester_context[0]
