"""Scenario builder for avatar-embodied WASM runtime over WHAM demo models."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

from world_foundation_model import (
    build_coding_agent_avatar_cast,
    build_world_foundation_model,
)

DEFAULT_SCENARIO_ID = "avatar-wasm-wham.runtime.v1"
DEFAULT_DEMO_MODELS: tuple[str, ...] = ("WHAM_A90", "WHAM_SF23", "WHAM_W14")


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def generate_wasd_control_module(module_name: str = "WhamWASDControlModule") -> str:
    """Generate a deterministic TypeScript WASD self-navigation module."""
    return f"""// Auto-generated by orchestrator.avatar_wasm_runtime_scenario
export type WASDKey = "W" | "A" | "S" | "D";

export interface Vec2 {{
  x: number;
  y: number;
}}

export interface AgentState {{
  x: number;
  y: number;
  speed: number;
}}

export interface ControlFrame {{
  activeKeys: WASDKey[];
  target: Vec2;
  reason: string;
}}

export class {module_name} {{
  static nextFrame(state: AgentState, target: Vec2, blockedKeys: Set<WASDKey> = new Set()): ControlFrame {{
    const dx = target.x - state.x;
    const dy = target.y - state.y;
    const horizontal = dx >= 0 ? "D" : "A";
    const vertical = dy >= 0 ? "W" : "S";
    const primary: WASDKey = Math.abs(dx) >= Math.abs(dy) ? horizontal : vertical;
    const secondary: WASDKey = primary === horizontal ? vertical : horizontal;

    const active: WASDKey[] = [];
    if (!blockedKeys.has(primary)) {{
      active.push(primary);
    }}
    if (active.length === 0 && !blockedKeys.has(secondary)) {{
      active.push(secondary);
    }}
    if (active.length === 0) {{
      return {{
        activeKeys: [],
        target,
        reason: "all_directions_blocked",
      }};
    }}

    return {{
      activeKeys: active,
      target,
      reason: "vector_guided_self_navigation",
    }};
  }}
}}
"""


def build_lora_reward_mechanism() -> dict[str, Any]:
    """Define reward signals used to fine tune LoRA adapters in runtime."""
    return {
        "objective": "maximize_navigation_success_with_retrieval_alignment",
        "weights": {
            "goal_progress": 0.45,
            "collision_penalty": -0.25,
            "motion_smoothness": 0.15,
            "rag_context_match": 0.20,
            "mcp_contract_compliance": 0.15,
        },
        "update_policy": {
            "method": "online_lora_rank_update",
            "rank": 16,
            "alpha": 32.0,
            "min_samples_per_update": 32,
            "max_updates_per_episode": 3,
        },
    }


def build_rag_api_scaffold() -> dict[str, Any]:
    """Scaffold MCP runtime API contracts for RAG and scenario execution."""
    return {
        "mcp_gateway": {"endpoint": "/tools/call", "method": "POST"},
        "tools": [
            {
                "name": "build_local_world_foundation_model",
                "purpose": "produce grounded worldline payload from prompt and git snapshot",
            },
            {
                "name": "get_coding_agent_avatar_cast",
                "purpose": "retrieve embodied avatar bindings for coding agents",
            },
            {
                "name": "submit_runtime_assignment",
                "purpose": "hand off runtime.assignment.v1 artifacts to runtime MCP",
            },
        ],
        "contracts": {
            "runtime_assignment_schema": "runtime.assignment.v1",
            "token_shape": "path, sha, chunk_index, source_type, grounding_tag",
            "retrieval_top_k_default": 5,
        },
    }


def build_avatar_embodiment_contract() -> dict[str, Any]:
    """Embodied-avatar operating contract for coding agents in the simulation."""
    return {
        "primary_goal": "complete WHAM navigation tasks through MCP-governed WASM runtime",
        "secondary_goals": [
            "generate deterministic WASD controls for self-navigation",
            "improve LoRA behavior with reward-gated RAG evidence",
            "preserve runtime.assignment.v1 and API contract integrity",
        ],
        "always": [
            "act through avatar-bound role identity",
            "emit replayable runtime traces for each frame decision",
            "use RAG context before applying LoRA updates",
        ],
        "never": [
            "issue tool calls outside registered MCP contracts",
            "apply LoRA updates without reward evidence and lineage hash",
            "discard avatar metadata during worker serialization",
        ],
        "when_uncertain": [
            "pause movement and request refreshed RAG context",
            "fallback to safe deterministic navigation policy",
            "mark runtime stage as blocked with explicit reason",
        ],
    }


def build_avatar_wasm_wham_scenario(
    *,
    prompt: str,
    repository: str,
    commit_sha: str,
    actor: str = "runtime_user",
    demo_models: Sequence[str] = DEFAULT_DEMO_MODELS,
) -> dict[str, Any]:
    """Create a working runtime scenario for avatar-based coding agents."""
    world_foundation = build_world_foundation_model(
        prompt=prompt,
        repository=repository,
        commit_sha=commit_sha,
        actor=actor,
        cluster_count=4,
    )
    avatar_cast = build_coding_agent_avatar_cast()
    wasd_source = generate_wasd_control_module()

    return {
        "scenario_id": DEFAULT_SCENARIO_ID,
        "created_at": _now_iso(),
        "mission": {
            "statement": (
                "Coding Agents embody runtime Avatars in a WASM loop, self-navigate "
                "WHAM demo models with generated WASD controls, and fine tune LoRA "
                "reward mechanisms using RAG-scaffolded MCP APIs."
            ),
            "success_criteria": [
                "runtime assignment can be submitted and replayed",
                "WASD control module is generated and deterministic",
                "LoRA reward update policy is attached to runtime telemetry",
            ],
        },
        "avatar_contract": build_avatar_embodiment_contract(),
        "avatars": avatar_cast,
        "world_foundation_model": world_foundation,
        "wasm_runtime": {
            "engine": "WASD GameEngine",
            "shell": "wasm",
            "render_backend": "webgl",
            "demo_models": list(demo_models),
            "wasd_control_module": {
                "path": "runtime/wasm/wham_wasd_control_module.ts",
                "language": "typescript",
                "source": wasd_source,
            },
        },
        "lora_reward_mechanism": build_lora_reward_mechanism(),
        "rag_api_scaffold": build_rag_api_scaffold(),
        "runtime_flow": [
            "ingest prompt and git snapshot",
            "build world foundation model with avatar cast",
            "emit runtime.assignment.v1 handoff",
            "generate WASD control frames per WHAM tick",
            "retrieve RAG chunks for policy correction",
            "compute reward and apply bounded LoRA updates",
            "publish MCP trace and scenario ledger",
        ],
    }


def materialize_avatar_wasm_wham_scenario(
    *,
    prompt: str,
    repository: str,
    commit_sha: str,
    actor: str,
    scenario_path: Path,
    wasd_module_path: Path,
) -> dict[str, str]:
    """Write scenario JSON + WASD module source to disk."""
    scenario = build_avatar_wasm_wham_scenario(
        prompt=prompt,
        repository=repository,
        commit_sha=commit_sha,
        actor=actor,
    )
    scenario_path.parent.mkdir(parents=True, exist_ok=True)
    wasd_module_path.parent.mkdir(parents=True, exist_ok=True)

    scenario_path.write_text(json.dumps(scenario, indent=2), encoding="utf-8")
    wasd_module_path.write_text(
        scenario["wasm_runtime"]["wasd_control_module"]["source"],
        encoding="utf-8",
    )
    return {
        "scenario_path": str(scenario_path),
        "wasd_module_path": str(wasd_module_path),
        "scenario_id": scenario["scenario_id"],
    }

