#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────
// Ghost Void Engine — Validation Report Generator
//
// Aggregates all validation results into a markdown report that
// gets posted as a PR comment and saved as an artifact.
// ─────────────────────────────────────────────────────────────────────

import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { join } from "path";

const ENGINE_TESTS = process.env.ENGINE_TESTS || "unknown";
const INTEGRATION_TESTS = process.env.INTEGRATION_TESTS || "unknown";
const CODE_QUALITY = process.env.CODE_QUALITY || "unknown";
const DETERMINISM = process.env.DETERMINISM || "unknown";

function statusIcon(status) {
  switch (status) {
    case "success":
      return "✅";
    case "failure":
      return "❌";
    case "skipped":
      return "⏭️";
    case "cancelled":
      return "🚫";
    default:
      return "❓";
  }
}

function overallStatus(statuses) {
  if (statuses.includes("failure")) return "FAILED";
  if (statuses.every((s) => s === "success")) return "PASSED";
  if (statuses.includes("skipped")) return "PARTIAL";
  return "UNKNOWN";
}

// ─── Build Report ───────────────────────────────────────────────────

const statuses = [ENGINE_TESTS, INTEGRATION_TESTS, CODE_QUALITY, DETERMINISM];
const overall = overallStatus(statuses);
const overallIcon = overall === "PASSED" ? "✅" : overall === "FAILED" ? "❌" : "⚠️";

const timestamp = new Date().toISOString();

let report = `# ${overallIcon} Game Validation Report

> **Status**: ${overall}
> **Generated**: ${timestamp}
> **Commit**: \`$\{process.env.GITHUB_SHA?.slice(0, 8) || "local"}\`

---

## Pipeline Results

| Stage | Status | Result |
|-------|--------|--------|
| 🧪 Engine Tests | ${statusIcon(ENGINE_TESTS)} | ${ENGINE_TESTS} |
| 🔗 Integration Tests | ${statusIcon(INTEGRATION_TESTS)} | ${INTEGRATION_TESTS} |
| 🔍 Code Quality | ${statusIcon(CODE_QUALITY)} | ${CODE_QUALITY} |
| 🔁 Determinism Check | ${statusIcon(DETERMINISM)} | ${DETERMINISM} |

---

## Test Log Excerpts

`;

// Collect logs from artifacts directory
const artifactsDir = "artifacts";
if (existsSync(artifactsDir)) {
  const dirs = readdirSync(artifactsDir, { withFileTypes: true }).filter((d) => d.isDirectory());

  for (const dir of dirs) {
    const dirPath = join(artifactsDir, dir.name);
    const files = readdirSync(dirPath).filter((f) => f.endsWith(".log"));

    for (const file of files) {
      const content = readFileSync(join(dirPath, file), "utf8");
      const lines = content.split("\n");
      const excerpt = lines.slice(-20).join("\n"); // last 20 lines

      report += `### 📄 ${file}\n\n`;
      report += "```\n";
      report += excerpt;
      report += "\n```\n\n";
    }
  }
} else {
  report += "*No artifact logs found.*\n\n";
}

// Recommendations
report += `---

## Recommendations

`;

if (ENGINE_TESTS === "failure") {
  report += `- ❌ **Engine tests failed** — check C++ compilation and assertion logic\n`;
}
if (INTEGRATION_TESTS === "failure") {
  report += `- ❌ **Integration tests failed** — verify engine binary and server compatibility\n`;
}
if (CODE_QUALITY === "failure") {
  report += `- ❌ **Code quality issues** — run \`cppcheck\` locally to see warnings\n`;
}
if (DETERMINISM === "failure") {
  report += `- ❌ **Determinism broken** — hash chain or synthesis is non-reproducible\n`;
}
if (overall === "PASSED") {
  report += `- ✅ All validation checks passed — this build is ready for merge\n`;
}

report += `
---

*Generated by the 🎮 Game Validation Agent*
`;

writeFileSync("validation-report.md", report);
console.log(`📊 Report written to validation-report.md (${report.length} bytes)`);
console.log(`Overall: ${overallIcon} ${overall}`);
