apiVersion: v1
kind: Namespace
metadata:
  name: vh2-dev
  labels:
    app.kubernetes.io/name: vh2-sovereign-validator
    environment: dev
    pod-security.kubernetes.io/enforce: baseline   # relaxed vs prod restricted
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-vh2-quota
  namespace: vh2-dev
spec:
  hard:
    requests.cpu:    "1"
    requests.memory: 512Mi
    limits.cpu:      "2"
    limits.memory:   1Gi
    pods:            "10"
