"""CLI utilities for release-candidate automation."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Sequence

from .release_candidate import ProductionReleaseAutomator, default_schema_root


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate and validate production release candidate artifacts")
    parser.add_argument("--adapter-input", type=Path, required=True, help="Path to adapter input JSON")
    parser.add_argument("--adapter-output", type=Path, required=True, help="Path to adapter output JSON")
    parser.add_argument("--gate-result", type=Path, help="Optional gate result JSON; autogenerated when omitted")
    parser.add_argument("--schema-root", type=Path, default=default_schema_root(), help="Directory containing schemas")
    parser.add_argument("--output-dir", type=Path, default=Path("runtime/release"), help="Directory to write artifacts")
    parser.add_argument("--expected-gate-hash", help="Fail when computed gate hash does not match this value")
    return parser


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text())


def main(argv: Sequence[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    automator = ProductionReleaseAutomator(args.schema_root)
    input_payload = _read_json(args.adapter_input)
    output_payload = _read_json(args.adapter_output)
    gate_result = _read_json(args.gate_result) if args.gate_result else None

    artifacts = automator.build_release_artifacts(input_payload, output_payload, gate_result)
    if args.expected_gate_hash:
        automator.assert_expected_hash(artifacts, args.expected_gate_hash)
    automator.write_artifacts(artifacts, args.output_dir)
    print(artifacts.gate_hash)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
