name: Agents Unit Tests

description: Setup Python and run compile + targeted pytest checks for agent pipeline

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

    - name: Compile check
      shell: bash
      env:
        PYTHONDONTWRITEBYTECODE: "1"
      run: python -m compileall -q .

    - name: Run agent/game tests
      shell: bash
      env:
        PYTHONDONTWRITEBYTECODE: "1"
      run: |
        pytest -q tests/test_full_pipeline.py tests/test_intent_engine.py tests/test_avatar_integration.py tests/test_game_model.py tests/test_webgl_integration.py tests/test_cicd_pipeline.py tests/test_mcp_server.py
