from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class MCPArtifact(BaseModel):
    """The universal data contract for A2A communication."""

    artifact_id: str = Field(..., description="Unique UUID for this specific output")
    parent_artifact_id: Optional[str] = Field(default=None, description="ID of parent artifact in lineage")
    agent_name: str = Field(default="UnknownAgent", description="Name of the agent that produced this artifact")
    version: str = Field(default="1.0.0", description="Schema version")
    type: str = Field(..., description="The kind of data: 'research_doc', 'code_solution', 'test_report'")
    content: Any = Field(..., description="The actual data payload generated by the agent")
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Storage for agent names, models used, etc.")


class AgentTask(BaseModel):
    """Used by the Orchestrator to define what an agent needs to do."""

    task_id: str
    instruction: str
    input_artifacts: Optional[List[str]] = None  # IDs of previous artifacts to use as context
    priority: int = 1
