from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List
from datetime import datetime

class MCPArtifact(BaseModel):
    """
    The universal data contract for A2A communication.
    """
    artifact_id: str = Field(..., description="Unique UUID for this specific output")
    type: str = Field(..., description="The kind of data: 'research_doc', 'code_solution', 'test_report'")
    content: str = Field(..., description="The actual data or text generated by the agent")
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Storage for agent names, models used, etc.")

class AgentTask(BaseModel):
    """
    Used by the Orchestrator to define what an agent needs to do.
    """
    task_id: str
    instruction: str
    input_artifacts: Optional[List[str]] = None  # IDs of previous artifacts to use as context
    priority: int = 1
